version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "AvinodeProxy-Dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rmzo4ad6ufsn"
s3_prefix = "AvinodeProxy-Dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"